- name: haproxy website
  hosts: lbservers
  tasks:
    - name: Start etcd
      service: name=etcd.service state=started
      sudo: yes
      sudo_user: root

    - name: Install docker-py
      pip: name=docker-py version=1.2.3

    - name: pull container
      raw: docker pull haproxy 

    - name: launch nginx container
      docker:
        image="haproxy"
        name="haproxy"
        ports="80:80"
        volumes="/home/core/nginx-html/haproxy.cfg:/haproxy.cfg"
        state=started
