- name: haproxy website
  hosts: lbservers
  tasks:
    - name: Start etcd
      service: name=etcd.service state=started
      sudo: yes
      sudo_user: root

    - name: Install docker-py
      pip: name=docker-py version=1.2.3

    - name: pull container
      raw: docker pull tutum/haproxy:latest

    - name: launch nginx container
      docker:
        image="tutum/haproxy"
        name="tutum-haproxy"
        ports="80:80"
