- name: haproxy website
  hosts: lbservers
  tasks:
   - name: Install docker-py
     pip: name=docker-py version=1.8.0
   - name: check or build image
     docker_image: >
       name="rock-haproxy"
       tag="haproxy"
       path="/home/core/working/haproxy"
       state=present
