- name: httpd 
  hosts: web
  tasks:
   - name: Install docker-py
     pip: name=docker-py version=1.8.0
   - name: check or build image
     docker_image: > 
       name="rock-httpd"
       tag="apache"
       path="/home/core/working/apache"
       state=present

